layout_spectrum: 0.1484061
typography_spectrum: 0.4366273
color:
  saturation: 0.3174006
  lightness: 0.6525242
  brandStrength: 1
  brandColors:
    - '#735D41'
    - '#000000'
    - '#E5BC7B'
    - '#FF841F'
    - '#BD9B65'
  rhythmicContrast: 0.1385099
name: Wolfsker2test
