name: Wolfsker2test
favicon: null
layout_spectrum: 0.52056
typography_spectrum: 0.4366273
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#735D41'
    - '#000000'
    - '#E5BC7B'
    - '#FF841F'
    - '#BD9B65'
  brandStrength: 1
  lightness: 0.6525242
  saturation: 0.3174006
  rhythmicContrast: 0.75
purpose: []
